#!/bin/bash

function syntax {
    echo "Syntax: $(basename $0) pattern [remote='origin']
        default remote is 'origin'"
    exit 1
}

[[ ! -d "$(pwd)/.git" ]] && echo -e "\033[0;31mNot a git folder\033[0m" && exit 1

[[ $# -eq 0 ]] && syntax

pattern="$1"
remote="${2:-origin}"

echo -e "· \033[0;32mLooking for branches on \033[1;36m$remote\033[0m"

branches=$(git branch --no-color -r|grep $remote\/|sed "s/\s*$remote\///g"|egrep ${pattern})

[[ -z $branches ]] && echo "Nothing to do" && exit 1

for branch in $branches
do
    echo -e "\033[1;33m * $branch\033[0m"
done

echo -en "\n\033[0;32mDo you want to delete those branches?\033[0m [y/n] "
read yn
[[ $yn =~ ^[^yYnN]$ || -z $yn ]] && echo -e "\033[1;31mWhat are you doing man, bad answer: $yn\033[0m" && exit 1
[[ $yn =~ ^[nN]$ ]] && echo -e "\033[1;32mMaybe next time...\033[0m" && exit 1

for branch in $branches
do
    echo -en "\033[0;32m * deleting: \033[1;33m$branch \033[0m"
    git branch -D $branch &>/dev/null && echo -en "\033[1;31m[local]\033[0m "
    git push $remote --delete $branch &>/dev/null && echo -en "\033[1;31m[$remote]\033[0m"
    echo
done

echo terminated
