#!/bin/bash
pgrep -x "ctags" && exit 1
rm -f ./.js.tags.* >/dev/null 2>&1
[ -d ./websrc/ ] && path='./websrc/js ./websrc/components' || path='./app/webroot/js'
(ctags -R --options=./.ctags.js.options -f ./.js.tags.$$ $path && sed -i -E "/^(if|switch|function|module\.exports|while|for|each|forEach|describe).+language:js$/d" ./.js.tags.$$ && mv -f ./.js.tags.$$ ./.js.tags ) &




#find . -type f -iregex ".*\.js[x]?$" -path "./app/webroot/*" -not -path "./app/webroot/min/*" -exec jsctags {} -f \; | sed '/^$/d' | sort > .js.tags
#FLAG='no'
#if [[ $# -eq 1 ]]; then
    #FLAG='yes'
#fi
#ctags --verbose=$FLAG --totals=$FLAG --recurse=yes --language-force=JavaScript --recurse -f ./.js.tags -L ./.ctags.js.inc --exclude=@./.ctags.js.exc
