#!/bin/bash
find . -type f -iregex ".*\.js$" -not -path "./*/node_modules/*" -exec jsctags {} -f \; | sed '/^$/d' | sort > .js.tags
#FLAG='no'
#if [[ $# -eq 1 ]]; then
    #FLAG='yes'
#fi
#ctags --verbose=$FLAG --totals=$FLAG --recurse=yes --language-force=JavaScript --recurse -f ./.js.tags -L ./.ctags.js.inc --exclude=@./.ctags.js.exc
