#!/bin/bash

FLAG='no'
if [[ $# -eq 1 ]]; then
    FLAG='yes'
fi
ctags --verbose=$FLAG --totals=$FLAG --recurse=yes --language-force=JavaScript --recurse -f ./.js.tags -L ./.ctags.js.inc --exclude=@./.ctags.js.exc 
