#!/bin/bash
pgrep -x "ctags" >/dev/null 2>&1 && exit 1
[[ -f ./.php.tags.$$ ]] && rm -f ./.php.tags.$$ >/dev/null 2>&1
(
    nice -n19 ionice -c2 -n7 ctags -R --options=./.ctags.php.options -f ./.php.tags.$$ .  && mv -f ./.php.tags.$$ ./.php.tags >/dev/null 2>&1
) &
