#!/usr/bin/env bash

#git clone git://git.launchpad.net/~ubuntu-kernel-test/ubuntu/+source/linux/+git/mainline-crack v4.9.4 75353ac8ff437322ca5520b28d9f9b4b41b39bd6
#wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.9.4/0001-base-packaging.patch
#wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.9.4/0002-UBUNTU-SAUCE-add-vmlinux.strip-to-BOOT_TARGETS1-on-p.patch
#wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.9.4/0003-UBUNTU-SAUCE-tools-hv-lsvmbus-add-manual-page.patch
#wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.9.4/0004-UBUNTU-SAUCE-no-up-disable-pie-when-gcc-has-it-enabl.patch
#wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.9.4/0005-debian-changelog.patch
#wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.9.4/0006-configs-based-on-Ubuntu-4.9.0-11.12.patch
git clone git://kernel.ubuntu.com/ubuntu/ubuntu-zesty.git
